# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b78105d5c0c5aaf8b986b986406e9c702bfc1dafeab8382a42ac1a563e2bd8ecc2decb0c4758e166864ef088c89bd475ff02be7f19e8739808b5e90aee55a3c

test:
  secret_key_base: 0a0598ce5556a52337faab87236ab4152731f99a5fa96107e868adbb7bf8af5e1e4bf4c04209e75e7535530157fc5d4947044351af1c5b1a49e236efd615c578

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
